plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"

nodeLinker: node-modules

yarnPath: .yarn/releases/yarn-3.1.1.cjs

npmRegistryServer: "https://registry.npm.taobao.org"
